"""14

Revision ID: 66826fa1f428
Revises: 95d8e19abe18
Create Date: 2023-11-21 16:44:10.277534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66826fa1f428'
down_revision: Union[str, None] = '95d8e19abe18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE task ALTER COLUMN distance TYPE INTEGER USING distance::integer;')
    # op.alter_column('task', 'distance',
    #            existing_type=sa.VARCHAR(length=150),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'distance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
