"""15

Revision ID: 8b4a3312cc48
Revises: 66826fa1f428
Create Date: 2023-11-21 16:51:50.371932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4a3312cc48'
down_revision: Union[str, None] = '66826fa1f428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'start_time',
               existing_type=sa.DATE(),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'start_time',
               existing_type=sa.String(length=150),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
