"""13

Revision ID: 95d8e19abe18
Revises: 6e7dd20159ec
Create Date: 2023-11-20 05:09:09.544431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d8e19abe18'
down_revision: Union[str, None] = '6e7dd20159ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('start_time', sa.Date(), nullable=False))
    op.add_column('task', sa.Column('end_time', sa.String(length=150), nullable=True))
    op.add_column('task', sa.Column('time_spent', sa.String(length=150), nullable=True))
    op.add_column('task', sa.Column('distance', sa.String(length=150), nullable=True))
    op.add_column('task', sa.Column('status', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    op.drop_column('task', 'distance')
    op.drop_column('task', 'time_spent')
    op.drop_column('task', 'end_time')
    op.drop_column('task', 'start_time')
    # ### end Alembic commands ###
