"""6

Revision ID: fd8c22b7d9b1
Revises: 98cd0ac6e2a6
Create Date: 2023-11-20 02:02:08.051137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8c22b7d9b1'
down_revision: Union[str, None] = '98cd0ac6e2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=False),
    sa.Column('mname', sa.String(length=150), nullable=False),
    sa.Column('lname', sa.String(length=150), nullable=False),
    sa.Column('phone_num', sa.String(length=150), nullable=False),
    sa.Column('driving_license', sa.String(length=150), nullable=False),
    sa.Column('registration_date', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver')
    # ### end Alembic commands ###
